### ISSUE TITLE
XcodeMLtools_Fmod is missing from this

### ISSUE THREAD

**Issue by clementval** [omni-compiler/xcodeml-tools#1]
@h-murai @mnakao I see that `XcodeMLtools_Fmod` is not part of the common jar ... Is that normal? I think it would be nice to have it.

**Comment by h-murai** [comment]
@clementval For this moment, this xcodeml-tools2 contains just tools needed to translate C/Fortran source to XcodeML (C_Front/F_Front) and XcodeML back to C/Fortran source (C_Back/F_back). `XcodeMLtools_Fmod` has a function of translating XcodeML to Xobjects (JAVA objects). So, I guess you don't need it in your project... Are you using `XcodeMLtools_Fmod` for any purposes?

**Comment by clementval** [comment]
@h-murai I'm using the `addSearchPath()` and `getSearchPath` methods. But I can replace this easily. So I don't really need it ...
