### ISSUE TITLE
F_Front deep_copy_id_types when importing module can take forever

### ISSUE THREAD

**Issue by clementval** [omni-compiler/xcodeml-tools#129]
This issue is one performance hit that can be linked to the broader performance issue #104. 

The following code takes really long time to go through the Fortran front-end. This is mainly happening in the `deep_copy_id_types` called from `import_module_ids` (both function are located in F-compile.c). 

The module used in the code snippet below is provided here (just uncompress it). 

[atlas_module.xmod.gz](https://github.com/omni-compiler/xcodeml-tools/files/2668444/atlas_module.xmod.gz)

```fortran
module mod1
  use atlas_module
end module mod1
```

@h-murai @mnakao Is there any plan in increasing the performance of the compiler from your side?

**Comment by clementval** [comment]
Most of the time is spent in the `type_is_replica` function has the list data structure here seems to be a bad choice in term of performance.

**Comment by h-murai** [comment]
@clementval It also looks to me that the list data is too strong. I wonder if a flag in TYPE_DESC works for the purpose. Anyway, we've had no plan yet and now recognized its seriousness.
