### ISSUE TITLE
PGI directives ignored by Fortran frontend

### ISSUE THREAD

**Issue by phmarti** [omni-compiler/xcodeml-tools#142]
PGI's proprietary Fortran directives `!pgi$` are not recognized by the Fortran frontend as directives and are ignored.

They are documented here: https://www.pgroup.com/resources/docs/18.10/x86/pgi-ref-guide/index.htm#dir-prag-pgi-proprietary

**Comment by h-murai** [comment]
@phmarti Ok. I'll try to make the frontend recognize and keep PGI's directives.

**Comment by h-murai** [comment]
@phmarti PGI directives are recognized with the `-pgi` option.
