### ISSUE TITLE
use xmpf_coarray_decl should be disable by default

### ISSUE THREAD

**Issue by clementval** [omni-compiler/xcodeml-tools#40]
As the repository has been splitted, the `xmpf` lib is not available by default and therefore, I would suggest to inverse the behavior of the flag managing this feature. One must enable this to have the `USE` statement added. 

What do you think @h-murai @mnakao ?

**Comment by h-murai** [comment]
@clementval I agree to you. I'll also change the behavior of omni-compiler.

**Comment by clementval** [comment]
resolve by #43
