### ISSUE TITLE
Continuous integration for testing

### ISSUE THREAD

**Issue by h-murai** [omni-compiler/xcodeml-tools#49]
@clementval @mnakao I'm considering we need continuous integration for testing. There are two scripts `check_test_diff.sh` and `compile_all_test.sh` for testing F_Front, but I have no idea how to set up it with these scripts.

We've already adopted Jenkins for omni-compiler, and I remember @clementval has proposed Travis-CI.

Do you have any idea?

**Comment by clementval** [comment]
@h-murai I think this is a very good idea. I opened the issue #38 in that sense. 

I can help you set this up with travis CI if you want. I think CI like travis is very nice because we can validate pull requests with it. It is easy to integrate it with github and to make sure tests are executed before one can merge a pull request. 

I think all the test data should be processed by the front-end and back-end and the resulting code should be compiled with simple gfortran in travis for example. This would be nice testing for any regression. 

Let me know if you need my help.

**Comment by h-murai** [comment]
@clementval Sorry that I missed your proposal, #38. Anyway, I'll consider your proposal, and decide the procedure ASAP.

**Comment by clementval** [comment]
@h-murai No problem! Looking forward to it. Feel free to close #38

**Comment by mnakao** [comment]
@clementval Thanks for your comment. I also think that the travis CI is best for the XcodeML-Tools project since it may be developed by various people.

**Comment by h-murai** [comment]
@clementval @mnakao Considering continuous integration for testing, we should choose a target version of gfortran as the backend compiler. Do you have any suggestions about this?

**Comment by clementval** [comment]
@h-murai @mnakao if you choose a tool like travis for example, it is quite easy to test out several version of a compiler. For example, in claw, I'm testing the toolchain with gfortran 5, 6 and 7. 
https://github.com/claw-project/claw-compiler/blob/master/.travis.yml

The system will automatically trigger 3 separate builds to test like shown here: https://travis-ci.org/claw-project/claw-compiler

But for sure, I think we should test with a gfortran version that supports F03 and F08 I think as there is quite some test data about it.

**Comment by h-murai** [comment]
@clementval @mnakao My concern is that it's troublesome to choose test codes depending on the version of the backend compiler. For example, a version of gfortran supports a part of the F2008 features and we have to skip such tests with it. Actually, `compile_all_test.sh` skips a test if a file `NAME.skip.native` is found.

Anyway, I think gfortran 7 is the candidate.

**Comment by clementval** [comment]
@h-murai @mnakao I agree. gfortran 7 or later is fine for me!

**Comment by h-murai** [comment]
@clementval @mnakao We set up Travis CI for testing. Now, after origin/master being updated, test is done (just for Fortran, for this moment) and the result is sent to the committer.

As you know, source programs in `F-FrontEnd/test/testdata` are the target, and the guideline for committers is as follows.

- Committers should put test codes in `F-FrontEnd/test/testdata` when committing any files.
- Our final goal is to move all of the codes in `F-FrontEnd/test/faileddata` to `F-FrontEnd/test/testdata` and to remove all `.skip.native` files in `F-FrontEnd/test/testdata`.

Some codes in `F-FrontEnd/test/faileddata` could be accepted by the latest version and some`.skip.native` files can be removed now, but I haven't investigated them yet. I'd like to do it in the near future.

**Comment by clementval** [comment]
@h-murai @mnakao That's a great news! I'm currently updating all PRs where you (@h-murai) had some comments and in the mean time trying this integration! That will help a lot the next developments.
If you want to had some security to the repository, I suggest to protect the master branch as shown in the picture below. You can then require the Travis CI to succeed before merge is possible. 

![screen shot 2018-07-16 at 11 45 17](https://user-images.githubusercontent.com/1507158/42752449-360cc302-88ee-11e8-86c9-7439bb8c6c91.png)

**Comment by mnakao** [comment]
@clementval Thank you for your advice. I check the function "Protected Branch."

**Comment by clementval** [comment]
@h-murai @mnakao I think the current setup works great! What would be the preferred workflow? I mean who is responsible to merge PRs that pass all the tests?
