### ISSUE TITLE
Redefinition of logical operator are not equivalent

### ISSUE THREAD

**Issue by clementval** [omni-compiler/xcodeml-tools#96]
#### Description of the problem
```fortran
module mo_operator
  implicit none
  private

  public :: operator(>)

  interface operator(>)
    module procedure greater_than
  end interface operator(>)

  type :: t1
    integer :: id
  end type t1

contains

  function greater_than(lhs, rhs) result(gt) 
    logical :: gt
    type(t1), intent(in) :: lhs
    type(t1), intent(in) :: rhs
    gt = lhs%id > rhs%id
  end function greater_than

end module mo_operator
```

```fortran
module mod1
  use mo_operator, only: operator(>)
end module mod1
```

The two modules above compiles fine with gfortran-7 but when you transformed only the second module, the compilation will fails. It fails because OMNI transform the logical operator `>` by the other fortran representation `.gt.` (see code below). This works well when all files are processed by OMNI but this is a way too high requirements. Imagine when you have libraries, you cannot imagine to process all those libraries with OMNI and recompile them. 

```fortran 
MODULE mod1
 USE mo_operator , ONLY: OPERATOR ( .gt. )
END MODULE mod1
```

```bash
mod1.f90:2:24:

   use mo_operator, only: operator(.gt.)
                        1
Error: Intrinsic operator '.gt.' referenced at (1) not found in module 'mo_operator'
```

#### Solution
We need to make the distinction between these operators in the AST and re-generate their correct form. This would require an extra attribute in the `binary element` of the XcodeML-F IR and some tweaks in the Fortran front-end and back-end.

**Comment by clementval** [comment]
@h-murai Any thought on this problem? I can start to work on it next week if you agree with my proposed solution.

**Comment by h-murai** [comment]
@clementval The "extra attribute" solution you proposed works well for the XMP translator. Yes, I agree with it. Please go ahead with it.

**Comment by h-murai** [comment]
@clementval In addition, I also think that we must be able to link files processed by Omni with those compiled by other compiler.

**Comment by clementval** [comment]
@h-murai Thanks for your quick reply. I'll start to work on it next week.
